%:
	+$(MAKE) $@ -C 01_intro
	+$(MAKE) $@ -C 02_functions_and_arrays
	+$(MAKE) $@ -C 03_more_on_pointers_and_vectors
	+$(MAKE) $@ -C 04_custom_types
	+$(MAKE) $@ -C 05_copy_move_semantics
	+$(MAKE) $@ -C 06_error_handling
	+$(MAKE) $@ -C 07_live
	+$(MAKE) $@ -C 08_inheritance


